name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List directory contents
        shell: pwsh
        run: |
          Write-Host "Current directory:"
          Get-ChildItem -Directory
          Write-Host "`nParent directory:"
          Get-ChildItem .. -Directory
      - name: Validate NuGet API Key
        shell: pwsh
        run: |
          if ($env:NUGET_KEY) {
            Write-Host "API key is set. Attempting dry run..."
            Publish-Module -Path ../DemoModule -NuGetApiKey $env:NUGET_KEY -WhatIf
          } else {
            Write-Error "API key is not set."
          }
        env:
          NUGET_KEY: ${{ secrets.DEMOMODULEPSG }}
      - name: Build and publish
        env:
          NUGET_KEYG: ${{ secrets.DEMOMODULEPSG }}
          BUILDVER: "0.1.0"
        shell: pwsh
        run: |
          ./build_scripts/build.ps1
          if (Test-Path ../DemoModule) {
            Publish-Module -Path ../DemoModule -NuGetApiKey $env:NUGET_KEY -Verbose
          } else {
            Write-Error "DemoModule folder not found."
          }
