jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: echo "Building..."

  publish-to-gallery:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.DEMOMODULEPSG }}
          BUILDVER: "1.0.0"
        shell: pwsh
        run: |
          ./build_scripts/build.ps1
          Publish-Module -path ./DemoModule -NuGetApiKey $env:NUGET_KEY -Verbose
