name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List directory contents
        shell: pwsh
        run: |
          Write-Host "Current directory:"
          Get-ChildItem -Directory
          Write-Host "`nParent directory:"
          Get-ChildItem .. -Directory
      - name: Validate NuGet API Key
        shell: pwsh
        run: |
          if ($env:POWERSHELL_GALLERY_API_KEY) {
            Write-Host "API key is set. Attempting dry run..."
            Publish-Module -Path ../DemoModule -Repository PSGallery -NuGetApiKey $env:POWERSHELL_GALLERY_API_KEY -WhatIf
          } else {
            Write-Error "API key is not set."
          }
        env:
          POWERSHELL_GALLERY_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
      - name: Build and publish
        env:
          POWERSHELL_GALLERY_API_KEY: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
          BUILDVER: "0.1.0"
        shell: pwsh
        run: |
          ./build_scripts/build.ps1
          if (Test-Path ../DemoModule) {
            Publish-Module -Path ../DemoModule -Repository PSGallery -NuGetApiKey ${{ secrets.POWERSHELL_GALLERY_API_KEY }} -verbose
          } else {
            Write-Error "DemoModule folder not found."
          }
